const KEY='ahmed-development-os-v3';
const TRACKS={ml:{name:'ML → AI',goal:10},software:{name:'Software Engineering',goal:7},diploma:{name:'Diploma',goal:6},language:{name:'Languages & Communication',goal:5},reading:{name:'Reading & Soft Skills',goal:3},quran:{name:'Quran / Personal',goal:4},fitness:{name:'Physical Activity',goal:14}};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),day=()=>new Date().toISOString().slice(0,10);
function fresh(){return{tasks:{},weekly:{},work:{},workStart:null,interviews:[],targets:Object.fromEntries(Object.entries(TRACKS).map(([k,v])=>[k,v.goal]))}}
function data(){try{return{...fresh(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return fresh()}}
function save(d){localStorage.setItem(KEY,JSON.stringify(d))}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$$('.reveal').forEach(x=>new IntersectionObserver(e=>e.forEach(v=>v.isIntersecting&&v.target.classList.add('show')),{threshold:.1}).observe(x));
document.addEventListener('mousemove',e=>{$$('.tilt:hover').forEach(c=>{const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;c.style.transform=`perspective(900px) rotateY(${x*5}deg) rotateX(${-y*5}deg) translateY(-7px)`})});document.addEventListener('mouseout',e=>{const c=e.target.closest?.('.tilt');if(c)c.style.transform=''});
function openOS(){location.href='dashboard.html'}function closeOS(){}
function tab(id,btn){$$('.pane').forEach(x=>x.classList.remove('active'));$$('.tab').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');btn.classList.add('active');renderAll()}
function weekStart(){const d=new Date(),n=d.getDay();d.setDate(d.getDate()-(n===6?0:n+1));return d.toISOString().slice(0,10)}
function workMinutes(){const d=data();let m=(d.work[day()]||[]).reduce((a,x)=>a+x.min,0);if(d.workStart)m+=(Date.now()-d.workStart)/60000;return m}
function weekMinutes(track){const d=data(),start=weekStart();let m=0;Object.entries(d.tasks).forEach(([date,arr])=>{if(date>=start)arr.forEach(t=>{if(t.done&&t.track===track)m+=Number(t.min)||0})});return m}
function devToday(){const d=data();return(d.tasks[day()]||[]).filter(t=>t.done&&t.track!=='fitness').reduce((a,t)=>a+(Number(t.min)||0),0)}
function fitToday(){const d=data();return(d.tasks[day()]||[]).filter(t=>t.done&&t.track==='fitness').reduce((a,t)=>a+(Number(t.min)||0),0)}
function renderDashboard(){const d=data();$('#workVal').textContent=(workMinutes()/60).toFixed(1)+'h';$('#devVal').textContent=(devToday()/60).toFixed(1)+'h';$('#fitVal').textContent=(fitToday()/60).toFixed(1)+'h';$('#todayLabel').textContent=new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'});$('#tracks').innerHTML=Object.entries(TRACKS).map(([k,v])=>{const a=weekMinutes(k)/60,g=Number(d.targets[k]??v.goal),p=Math.min(100,a/Math.max(g,1)*100);return`<div class="trackrow"><header><span>${v.name}</span><span>${a.toFixed(1)} / ${g}h</span></header><div class="bar"><i style="width:${p}%"></i></div></div>`}).join('');renderTimer()}
function renderTimer(){const e=$('#timer');if(!e)return;let s=Math.floor(workMinutes()*60);e.textContent=[Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,'0')).join(':');$('#timerBtn').textContent=data().workStart?'Stop session':'Start work'}
function toggleWork(){const d=data();if(d.workStart){const min=Math.max(1,Math.round((Date.now()-d.workStart)/60000));(d.work[day()]??=[]).push({at:Date.now(),min});d.workStart=null}else d.workStart=Date.now();save(d);renderAll()}
function addWork(){const n=Number(prompt('Minutes worked?','60'));if(!n)return;const d=data();(d.work[day()]??=[]).push({at:Date.now(),min:n});save(d);renderAll()}
function addTask(){const name=$('#taskName').value.trim(),track=$('#taskTrack').value,min=Number($('#taskMin').value)||30;if(!name)return;const d=data();(d.tasks[day()]??=[]).push({id:Date.now(),name,track,min,done:false});save(d);$('#taskName').value='';renderTasks();renderDashboard()}
function renderTasks(){const d=data(),arr=d.tasks[day()]||[];$('#taskList').innerHTML=arr.length?arr.map(t=>`<div class="task ${t.done?'done':''}"><button class="check" onclick="toggleTask(${t.id})">${t.done?'✓':'○'}</button><div class="taskname">${esc(t.name)}<small> · ${esc(TRACKS[t.track]?.name||t.track)} · ${t.min}m</small></div><button class="del" onclick="delTask(${t.id})">×</button></div>`).join(''):'<p class="note">No tasks yet. Add flexible blocks; the weekly balance matters more than a rigid clock.</p>'}
function toggleTask(id){const d=data(),t=(d.tasks[day()]||[]).find(x=>x.id===id);if(t)t.done=!t.done;save(d);renderAll()}function delTask(id){const d=data();d.tasks[day()]=(d.tasks[day()]||[]).filter(x=>x.id!==id);save(d);renderAll()}
function loadDay(){const d=data();if((d.tasks[day()]||[]).length&&!confirm('Add the default plan to existing tasks?'))return;const p=[['ML / AI learning','ml',90],['Software engineering depth','software',60],['Diploma study','diploma',60],['English / communication','language',30],['Read current book','reading',30],['Quran review','quran',30],['Walk / gym / outdoor activity','fitness',120]];(d.tasks[day()]??=[]).push(...p.map(([name,track,min],i)=>({id:Date.now()+i,name,track,min,done:false})));save(d);renderAll()}
function renderWeekly(){const d=data();$('#weeklyGrid').innerHTML=Object.entries(TRACKS).map(([k,v])=>{const a=weekMinutes(k)/60,g=Number(d.targets[k]??v.goal),p=Math.min(100,a/Math.max(g,1)*100);return`<div class="dashcard"><small>${v.name}</small><b>${a.toFixed(1)} / ${g}h</b><div class="bar"><i style="width:${p}%"></i></div><div style="margin-top:12px"><input class="input" style="max-width:90px" type="number" step=".5" value="${g}" onchange="target('${k}',this.value)"> <span class="note">weekly target</span></div></div>`}).join('')}
function target(k,v){const d=data();d.targets[k]=Number(v)||0;save(d);renderAll()}
function addInterview(){const type=$('#iType').value,score=Math.min(10,Math.max(0,Number($('#iScore').value)||0)),weak=$('#iWeak').value.trim(),notes=$('#iNotes').value.trim(),d=data();d.interviews.unshift({id:Date.now(),date:day(),type,score,weak,notes});save(d);$('#iScore').value=$('#iWeak').value=$('#iNotes').value='';renderInterviews()}
function renderInterviews(){const d=data(),start=weekStart(),count=d.interviews.filter(x=>x.date>=start).length;$('#interviewCount').textContent=count+' / 2 this week';$('#interviews').innerHTML=d.interviews.length?d.interviews.map(x=>`<div class="interview"><span class="score">${x.score}/10</span><b>${esc(x.type)}</b><div class="note">${x.date}</div><p><small>Improve:</small> ${esc(x.weak||'—')}</p><div class="note">${esc(x.notes)}</div></div>`).join(''):'<p class="note">No mock interviews logged yet.</p>'}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data(),null,2)],{type:'application/json'}));a.download='ahmed-development-os.json';a.click();URL.revokeObjectURL(a.href)}
function resetData(){if(confirm('Reset all Development OS data on this browser?')){localStorage.removeItem(KEY);renderAll()}}
async function notifications(){if(!('Notification'in window))return alert('Notifications are not supported here.');const p=await Notification.requestPermission();if(p==='granted')new Notification('Development OS',{body:'Local reminders enabled while this site is active.'})}
function reminder(){if(!('Notification'in window)||Notification.permission!=='granted'||new Date().getHours()<20)return;const pending=(data().tasks[day()]||[]).filter(x=>!x.done),k='ados-v3-'+day();if(pending.length&&!sessionStorage.getItem(k)){new Notification('Development OS',{body:pending.length+' unfinished tasks today.'});sessionStorage.setItem(k,'1')}}
function renderAll(){renderDashboard();renderTasks();renderWeekly();renderInterviews();const d=data();$('#sessions').textContent=(d.work[day()]||[]).map(x=>x.min+'m').join(' · ')||'No completed work sessions yet.'}
setInterval(()=>{renderTimer();reminder()},1000);
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeOS();if(!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){window._typed=(window._typed||'')+e.key.toLowerCase();window._typed=window._typed.slice(-8);if(window._typed.includes('ahmedos')){window._typed='';openOS()}}});
