const KEY='ahmed-os-fixed-v2';
const plans={
0:[['ML / AI',90,'ml'],['Software Engineering',90,'software'],['Postgraduate Diploma',60,'diploma'],['English & Communication',30,'language'],['Reading & Soft Skills',30,'reading']],
1:[['ML / AI',90,'ml'],['Software Engineering',60,'software'],['Postgraduate Diploma',60,'diploma'],['English & Communication',60,'language'],['Quran / Personal',30,'quran']],
2:[['ML / AI',90,'ml'],['Software Engineering',60,'software'],['Postgraduate Diploma',60,'diploma'],['English & Communication',30,'language'],['Reading & Soft Skills',30,'reading'],['Quran / Personal',30,'quran']],
3:[['ML / AI',90,'ml'],['Software Engineering',60,'software'],['Postgraduate Diploma',60,'diploma'],['English & Communication',60,'language'],['Quran / Personal',30,'quran']],
4:[['ML / AI',60,'ml'],['Software Engineering',60,'software'],['Postgraduate Diploma',60,'diploma'],['English & Communication',60,'language'],['Reading & Soft Skills',30,'reading'],['Quran / Personal',30,'quran']],
5:[['ML / AI',60,'ml'],['Software Engineering',30,'software'],['English & Communication',30,'language'],['Reading & Soft Skills',90,'reading'],['Quran / Personal',90,'quran']],
6:[['ML / AI',120,'ml'],['Software Engineering',60,'software'],['Postgraduate Diploma',60,'diploma'],['English & Communication',30,'language'],['Quran / Personal',30,'quran']]
};
const targets={ml:['ML → AI',600],software:['Software',420],diploma:['Diploma',360],language:['Language',300],reading:['Reading',180],quran:['Quran',240]};
const localKey=(d=new Date())=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
function state(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}}function save(x){localStorage.setItem(KEY,JSON.stringify(x))}
function todayPlan(){return plans[new Date().getDay()]}
function toggle(i){const s=state(),k=localKey(),d=s[k]||{done:[],physical:false};d.done=d.done.includes(i)?d.done.filter(x=>x!==i):[...d.done,i];s[k]=d;save(s);render()}
function togglePhysical(){const s=state(),k=localKey(),d=s[k]||{done:[],physical:false};d.physical=!d.physical;s[k]=d;save(s);render()}
function weekStart(){const d=new Date(),n=d.getDay(),back=(n+1)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-back);return d}
function completedByTrack(){const out={ml:0,software:0,diploma:0,language:0,reading:0,quran:0},s=state(),start=weekStart();for(let n=0;n<7;n++){const d=new Date(start);d.setDate(start.getDate()+n);const rec=s[localKey(d)]||{done:[]};(rec.done||[]).forEach(i=>{const task=plans[d.getDay()][i];if(task)out[task[2]]+=task[1]})}return out}
function render(){const s=state(),k=localKey(),d=s[k]||{done:[],physical:false},p=todayPlan();document.querySelector('#todayTasks').innerHTML=p.map((t,i)=>'<article class="task '+(d.done.includes(i)?'done':'')+'"><button onclick="toggle('+i+')">'+(d.done.includes(i)?'✓':'○')+'</button><div><h3>'+t[0]+'</h3><p>Fixed '+t[1]+' minute block</p></div><span>'+Math.floor(t[1]/60)+'h '+(t[1]%60?t[1]%60+'m':'')+'</span></article>').join('');const devDone=d.done.reduce((a,i)=>a+(p[i]?.[1]||0),0);document.querySelector('#done').textContent=Math.round(devDone/300*100)+'%';const pb=document.querySelector('#physicalBtn');pb.textContent=d.physical?'✓ Completed':'Mark complete';pb.classList.toggle('complete',!!d.physical);const done=completedByTrack();document.querySelector('#weekGrid').innerHTML=Object.entries(targets).map(([k,v])=>'<article><small>'+v[0]+'</small><b>'+v[1]/60+'h</b><span>'+ (done[k]/60).toFixed(1)+'h done</span></article>').join('');document.querySelector('#weekProgress').innerHTML=Object.entries(targets).map(([k,v])=>'<div><header><span>'+v[0]+'</span><span>'+(done[k]/60).toFixed(1)+' / '+v[1]/60+'h</span></header><i><b style="width:'+Math.min(100,done[k]/v[1]*100)+'%"></b></i></div>').join('')}
document.querySelector('#date').textContent=new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'short'});document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.pane').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.tab).classList.add('active')});render();